In [1]:
import numpy as np

In [4]:
# creating array 
data = [1, 2, 3, 4, 5]
data

[1, 2, 3, 4, 5]

In [5]:
arr = np.array(data)

In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
# multi dimensional arrays
data1 = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
arr1 = np.array(data1)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
# check dimension of array
arr1.ndim

2

In [14]:
# check shape of the array 
arr.shape

(5,)

In [15]:
# check datatype of an array
arr.dtype

dtype('int64')

In [16]:
# type casting
arr3 = np.array(data1, dtype=np.float64)

In [17]:
arr3

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [18]:
arr3.dtype

dtype('float64')

In [21]:
# create empty array
empty_arr = np.empty(2)
empty_arr

array([7.62198311e-312, 0.00000000e+000])

In [23]:
# create array ones only
ones_arr = np.ones([2, 3])

In [25]:
ones_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
# create array of zeroes only
zeroes_arr = np.zeros([2, 5])
zeroes_arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
zeroes_arr.dtype

dtype('float64')

In [32]:
zeroes_arr.astype(np.int64)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])