In [1]:
import numpy as np

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[:3]

array([0, 1, 2])

In [8]:
# assign values to a slice
arr[:3] = 100
arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9])

In [11]:
# distinction
arr_slice = arr[2:8]
arr_slice

array([100,   3,   4,   5,   6,   7])

In [12]:
arr_slice[2] = 1000
arr_slice

array([ 100,    3, 1000,    5,    6,    7])

In [13]:
arr

array([ 100,  100,  100,    3, 1000,    5,    6,    7,    8,    9])

In [15]:
# indexing in 3d array
arr_3d = np.array([
    [
        [1, 2, 3], 
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]   
])
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
arr_3d.shape

(2, 2, 3)

In [18]:
arr_3d[0] #2d

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr_3d[0][0] #1d

array([1, 2, 3])

In [22]:
arr_3d[0][0][0] 

np.int64(1)