In [1]:
import numpy as np

In [2]:
# vectorization
points = np.arange(-3, 3)
points

array([-3, -2, -1,  0,  1,  2])

In [3]:
xs, ys = np.meshgrid(points, points)

In [4]:
xs

array([[-3, -2, -1,  0,  1,  2],
       [-3, -2, -1,  0,  1,  2],
       [-3, -2, -1,  0,  1,  2],
       [-3, -2, -1,  0,  1,  2],
       [-3, -2, -1,  0,  1,  2],
       [-3, -2, -1,  0,  1,  2]])

In [5]:
ys

array([[-3, -3, -3, -3, -3, -3],
       [-2, -2, -2, -2, -2, -2],
       [-1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2]])

In [8]:
np.square(xs)

array([[9, 4, 1, 0, 1, 4],
       [9, 4, 1, 0, 1, 4],
       [9, 4, 1, 0, 1, 4],
       [9, 4, 1, 0, 1, 4],
       [9, 4, 1, 0, 1, 4],
       [9, 4, 1, 0, 1, 4]])

In [10]:
np.square(ys)

array([[9, 9, 9, 9, 9, 9],
       [4, 4, 4, 4, 4, 4],
       [1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1],
       [4, 4, 4, 4, 4, 4]])

In [11]:
s = np.square(xs) + np.square(ys)
s

array([[18, 13, 10,  9, 10, 13],
       [13,  8,  5,  4,  5,  8],
       [10,  5,  2,  1,  2,  5],
       [ 9,  4,  1,  0,  1,  4],
       [10,  5,  2,  1,  2,  5],
       [13,  8,  5,  4,  5,  8]])