### Numpy Basics

Numpy, short for numerical python, is the fundamental package required for high performance scientific computing and data analysis.

#### Importing **Numpy**
I am using `import numpy as np` convention however, you are free to use `from numpy import *` too

In [1]:
import numpy as np

#### Numpy ***ndarray*** : A multidimensional array object
N-dimensional array object, or ndarray, which is a fast, flexible container for large data sets in python.
An *ndarray* is a genric multidimensional container for ***homogenous*** data, that is, all of the elements must be of same type.

#### Creating ndarrays
A ***ndarray*** of n dimension can be created using a *array function*.
A array function is used for converting a sequence of data into an array object.  

In [2]:
# sequential data
data = [1, 2, 3, 4, 5]

In [3]:
arr1 = np.array(data)
arr1

array([1, 2, 3, 4, 5])

#### Multidimensional array
We can create a multi-dimensional array using nested sequence of data, like a ***list*** of equal-length lists.

In [4]:
data2 = [[1, 2, 3, 4],
         [5, 6, 7, 8]] # a nested list sequence of equal lists

In [5]:
arr2 = np.array(data2)

In [6]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

#### Basic Objects & Functions

1. ndim : `ndim` method can be used to find the dimensions of an array


In [7]:
data3 = [[1, 2, 3, 4],
         [5, 6, 7, 8]]

In [8]:
arr3 =  np.array(data3)
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr3.ndim # dimension of array

2

2. shape : `np.shape` method is used to find the shape of the ndarray

In [10]:
arr3.shape

(2, 4)

4. dtype : `np.dtype` is a method used for identifing the data type of an ndarray

In [11]:
arr3.dtype

dtype('int64')

#### Some of the additional method for creating ndarray's
In addition to `np.array` we can create an ndarray using,

1. **np.zeros** = `np.zeros(size)` method is used for creating an array of 0's of specified size.

In [12]:
arr4 = np.zeros(10)
arr4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
arr5 = np.zeros((2, 5)) # multi dimensional size of array should be specified in brackets
arr5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

2. **np.ones(size)** : `np.ones(size)` method is used for creating an array of 1's of specified size

In [14]:
arr6 = np.ones(10)
arr6

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
arr7 = np.ones((2, 5)) 
arr7

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
arr7.dtype 

dtype('float64')

3. **np.empty(size)** : `np.empty(size)` method is used for creating an empty array, usually consisting garbage value.

In [17]:
arr8 = np.empty((5, 5))
arr8

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

4. **np.arange** : `np.arange` method is used for creating an array of range of numbers. It is based on built-in `range` function.

In [18]:
arr9 = np.arange(10)
arr9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])