## Data Types for **ndarrays**

The **data type** or `dtype` is a special object containing the information the **ndarray** needs to interpret a chunk of memory as a particular type of data.

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4, 5], dtype=np.int32)
arr1

array([1, 2, 3, 4, 5], dtype=int32)

In [3]:
arr2 = np.array([6, 7, 8, 9, 10], dtype=np.float64)
arr2

array([ 6.,  7.,  8.,  9., 10.])

In [4]:
arr1.dtype

dtype('int32')

In [5]:
arr2.dtype

dtype('float64')

#### Type-Casting

We can convert or type cast one dtype to another dtype of **ndarray** using `astype` method.

In [6]:
arr3 = np.array([1, 2, 3, 4, 5], dtype=np.int64)

In [7]:
arr3

array([1, 2, 3, 4, 5])

In [8]:
arr3.dtype

dtype('int64')

In [9]:
float_arr3 = arr3.astype(dtype=np.float64)
float_arr3

array([1., 2., 3., 4., 5.])

In [10]:
float_arr3.dtype

dtype('float64')

In [11]:
data1 = [1.23, 3.43, 23.4, 54.89] # float array
data2 = ['1', '2', '3', '4', '5'] # string array

In [12]:
arr4 = np.array(data1)
arr5 = np.array(data2)

In [13]:
arr4

array([ 1.23,  3.43, 23.4 , 54.89])

In [14]:
arr5

array(['1', '2', '3', '4', '5'], dtype='<U1')

#### Converting `float` to `int`
When converting ndarry with floating point  numbers to `int`, the floating digits will be truncated.

In [15]:
int_arr4 = arr4.astype(dtype=np.int64) # truncates floating point digits

In [16]:
int_arr4

array([ 1,  3, 23, 54])

In [17]:
int_arr4.dtype

dtype('int64')

#### Convert `string` to `number`

In [18]:
int_arr5 = arr5.astype(dtype=np.int64)

In [19]:
int_arr5

array([1, 2, 3, 4, 5])