## Operations between `ndarrays` and Scalars
Arrays enable you to express batch operations on data without writing any for loops, this is called as *vectorization*

#### Airthmatic Operations on `ndarrays`

In [1]:
import numpy as np

In [2]:
data = [[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10]]

In [3]:
arr1 = np.array(data)

In [4]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [5]:
arr2 = arr1 * arr1

In [6]:
arr2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

In [7]:
arr3 = arr1 + arr1

In [8]:
arr3

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])