#### Basic Indexing and Slicing
Indexing in ndarrays allows us to select a subset of your data or individual elements.
Indexing of *One-Dimensional* array is similar to python-lists:

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# accessing single element
arr[5]

np.int64(5)

In [5]:
# slice of array
arr[5:8]

array([5, 6, 7])

#### Assigning a scalar value to a slice
When we assign a scalar value to a selected slice, the value is propagated to the entire selection.
for example:

In [6]:
arr[5:8] = 11

In [7]:
arr

array([ 0,  1,  2,  3,  4, 11, 11, 11,  8,  9])

As you can see the elements from 5th index to 8th (5:8) index have been changed to `11`.

***Note :*** We can copy a slice of an ndarray instead of *view* using `copy()` method. 

#### Distinction between `arrays` and `Lists`
First distinction from lists to arrays it that array slices are `views` on the original array. This means that the data is not copied, and any changes made to the view will be reflected on the source array.

In [8]:
arr_slice = arr[5:8]

In [9]:
arr_slice

array([11, 11, 11])

In [10]:
arr_slice[1] = 123

In [11]:
arr_slice

array([ 11, 123,  11])

In [12]:
arr

array([  0,   1,   2,   3,   4,  11, 123,  11,   8,   9])

as you can see every modification we made to the slice `arr_slice` is reflected to original source array.
furthermore,

In [13]:
arr_slice[:] = 20

In [14]:
arr_slice

array([20, 20, 20])

In [15]:
arr

array([ 0,  1,  2,  3,  4, 20, 20, 20,  8,  9])

## Indexing in 2-D Arrays
Indexing in two dimensional arrays is bit different than indexing in one dimensional arrays:

In [16]:
# 2-D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [17]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr_2d[1:2]

array([[4, 5, 6]])

In [19]:
arr_2d[2]

array([7, 8, 9])

In [20]:
arr_2d[1][1]

np.int64(5)

## Indexing in multi-dimensional arrays
In multi-dimensional arrays, if you omit later indices, the returning object will be a lower dimensional ndarray consisting of all the data along the higher dimensions.
for example, in 2 x 2 x 3 array:

In [21]:
arr_3d = np.array([
    [[1, 2, 3], 
     [4, 5, 6]],
    
    [[7, 8, 9], 
     [10, 11, 12]]
])

In [22]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

***Case 1:*** Here, `arr[0]` and `arr[1]` are **2 x 3** dimensional arrays :

In [23]:
arr_3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
arr_3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

***Case 2:*** Here, `arr[0][0]`, `arr[0][1]`, `arr[1][0]` and `arr[1][1]` are one dimensional arrays

In [25]:
arr_3d[0][0]

array([1, 2, 3])

In [26]:
arr_3d[0][1]

array([4, 5, 6])

In [27]:
arr_3d[1][0]

array([7, 8, 9])

In [28]:
arr_3d[1][1]

array([10, 11, 12])

In [29]:
for i in range(2):
    for j in range(2):
        for k in range(3):
            value = arr_3d[i][j][k]
            print(value, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [30]:
for i in range(2):
    for j in range(2):
        value = arr_3d[i][j]
        print(value)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


## Indexing with slices
Like other indexing in objects like python lists, ndarrays can be sliced in the same way:

In [31]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr_2d[2, 1:]

array([8, 9])

In [33]:
arr_2d[:, :1]

array([[1],
       [4],
       [7]])

of course, assigning to a slice expression assigns to the whole selection:

In [34]:
arr_2d[1:2, :] = 77

In [35]:
arr_2d

array([[ 1,  2,  3],
       [77, 77, 77],
       [ 7,  8,  9]])