## Boolean Indexing
Boolean indexing allows you to filter and manipulate arrays using boolean conditions. Essentially, you create a boolean array (an array of `True` and `False` values) that corresponds to the elements of the original array, and then use this array to select or modify elements based on a condition.

In [1]:
import numpy as np
from numpy import random

In [2]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

We can use `randn` function in **numpy.random** to generate some random distributed data:

In [3]:
data = np.random.randn(7, 4)

In [4]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [5]:
data

array([[ 0.184254  ,  1.60475589, -1.12338602,  0.40250291],
       [-1.80059066, -1.46157755,  0.07471401,  1.06741673],
       [ 0.2627655 , -0.58555423, -0.14485684, -0.55219194],
       [-0.55100244,  1.52174263, -0.05710157, -0.85654068],
       [ 0.78514061, -0.60089945,  0.51590075, -0.75427714],
       [-2.81015339,  0.94796915,  0.13811275, -0.09761996],
       [ 0.49256662, -0.11772679, -1.20926132,  0.88137844]])

Below code returns a boolean array with True on positions where `name = Bob` and false when `name != Bob`.

In [6]:
names == "Bob" 

array([ True, False, False,  True, False, False, False])

This boolean array can be passed when indexing the `data` array.

In [7]:
data[names == 'Bob']

array([[ 0.184254  ,  1.60475589, -1.12338602,  0.40250291],
       [-0.55100244,  1.52174263, -0.05710157, -0.85654068]])

#### Case 1: 
We can even mix and match boolean arrays with slices or integers:

In [8]:
data[names == 'Bob', 2:]

array([[-1.12338602,  0.40250291],
       [-0.05710157, -0.85654068]])

Above statement returns an array containing the subarrays from `data` based on indexing using `names` array.
since `names` array contains 7 elements, it first selects all the  elements of the `data` array and checks the condition `names == 'Bob'` if **True** then, it selects the elements from `data` corresponding to **True** value. 
Secondly, it selects the particular elements from the resulting array using `2:`.

#### Case 2: 
Select everything but 'Bob' (a certain name) using `!=` or negate the condition using `~`:

In [9]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [10]:
data[~(names == 'Bob')] 

array([[-1.80059066, -1.46157755,  0.07471401,  1.06741673],
       [ 0.2627655 , -0.58555423, -0.14485684, -0.55219194],
       [ 0.78514061, -0.60089945,  0.51590075, -0.75427714],
       [-2.81015339,  0.94796915,  0.13811275, -0.09761996],
       [ 0.49256662, -0.11772679, -1.20926132,  0.88137844]])

Above statement returns the elements from the `data` array corresponding to the value of given condtion `~[names == 'Bob']` i.e., False values

#### Case 3: 
Select multiple names to combne multiple boolean condition arithmatic operators `&`(and) and `|`(or).

In [11]:
mask = (names == 'Bob') | (names == 'Will')

mask

In [12]:
data[mask]

array([[ 0.184254  ,  1.60475589, -1.12338602,  0.40250291],
       [ 0.2627655 , -0.58555423, -0.14485684, -0.55219194],
       [-0.55100244,  1.52174263, -0.05710157, -0.85654068],
       [ 0.78514061, -0.60089945,  0.51590075, -0.75427714]])

#### Case 5:
Set values with boolean arrays:

In [13]:
data[data < 0] = 0

Sets all of the negative values in data to 0.