# Fancy Indexing
*Fancy Indexing* is a term adopted by NumPy to describe indexing using integer arrays.

In [1]:
import numpy as np

In [2]:
arr = np.empty((8, 4))

In [5]:
for i in range(8):
    arr[i] = i

In [6]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

## Case 1: 
Select rows in desired order using ndarray of integers

In [7]:
arr[[2, 4, 6]]

array([[2., 2., 2., 2.],
       [4., 4., 4., 4.],
       [6., 6., 6., 6.]])

## Case 2:
Use negative indexing with desired order

In [8]:
arr[[-6, -5, -4]]

array([[2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

## Case 3:
Pass mulitple index using ndarrays of integers

In [10]:
arr2 = np.arange(32).reshape((8, 4))
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [11]:
arr2[[0, 2, 4, 6], [0, 1, 2, 3,]]

array([ 0,  9, 18, 27])

In above output, the elements (0, 0), (2, 1), (4, 2) and (6, 3) were selected.

## Case 4:
Using `np.ix_()` function which converts two 1D integer arrays to a indexer thet selects the square region.

In [12]:
arr2[np.ix_([1, 2, 3, 4], [0, 1, 2, 3])]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])