## Transposing arrays and Swapping Axes

Transposing is a form of reshaping which returns a view on the underlying data without copying anything.

In [1]:
import numpy as np

In [2]:
arr = np.arange(15).reshape((3, 5))

In [3]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

For higher dimensional arrays, **Transpose** will accept a tuple of axis numbers to permute the axes.

In [5]:
# 3-D array
arr2 = np.arange(16).reshape((2, 2, 4))

In [6]:
arr2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [11]:
arr2.transpose((1, 0 ,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

## Swapping Axes

Swapping axes uses a method `swapaxes` which takes a pair of axis numbers:

In [13]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
arr.swapaxes(0, 1)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])