## Universal Functions: Fast Element-wise Array Functions
A **ufunc** (universal functions), is a function that performs element-wise operations on data in ndarray.

In [1]:
import numpy as np
from numpy import random

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Unary Functions
abs, fabs, sqrt, square, exp, log, modf etc.

**1. sqrt:** Gives the square root of every element in an array

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

**2. square:** returns square of every element number in a array

In [6]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

### Binary Functions 
add, subtract, multiply, divide, floor_divide, power, maximum, minimum, greater, greater_equal, less, less_equal, equal, not_equal, logical_and, logical_or, logical_xor etc. 

In [7]:
x = np.arange(10)
y = random.randn(10)

In [8]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
y

array([-0.43936479,  0.0112331 , -1.09471677, -2.08693864, -1.4785967 ,
        0.44136688,  0.14234578,  0.18654122,  0.76943712,  1.04004914])

**1. maximum(array1, array2)**: Returns element-wise maximum from both arrays

In [10]:
np.maximum(x, y) # element-wise maximum

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])