# Express Conditional Logic as Array Operations
***numpy.where*** function is a vectorized version of the ternary expressions `x if condition else y`.

In [1]:
import numpy as np

In [2]:
arr = np.random.randn(4, 4)

In [3]:
arr

array([[ 0.48586089,  1.32522804, -0.29587506, -1.87262472],
       [ 1.28003038, -0.96740364,  0.44273751,  0.74021442],
       [ 0.43359123,  1.50400424, -0.82521396, -0.8006623 ],
       [-1.22025536, -0.46597261,  0.26021863,  0.69347575]])

Here, we have a matrix of random numbers in which I want to replace all the random negative values with -2 and all the positive values with 2. we can use `numpy.where()` function to get this behaviour: 

In [4]:
np.where((arr>0), 2, -2)

array([[ 2,  2, -2, -2],
       [ 2, -2,  2,  2],
       [ 2,  2, -2, -2],
       [-2, -2,  2,  2]])

Above statement can be understood with following approach:

In [8]:
for i in range(4):
    for j in range(4):
        if arr[i][j] > 0:
            arr[i][j] = 1
        else: 
            arr[i][j] = -1
print(arr)

[[ 1.  1. -1. -1.]
 [ 1. -1.  1.  1.]
 [ 1.  1. -1. -1.]
 [-1. -1.  1.  1.]]
