# Statistical Methods
A set of mathematical functions which computes statistics about an entire array or about the data along an axis are accessible as array methods.

In [1]:
import numpy as np
from numpy import random

In [2]:
arr = np.arange(0, 20).reshape(5, 4) # normally distributed data
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

## 1. Mean
Mean can take an optional *axis* argument and computes over the given axis.
It results in an array with one fewer dimensions:

In [3]:
np.mean(arr)

np.float64(9.5)

In [4]:
arr.mean(axis=1) # computes at first axis

array([ 1.5,  5.5,  9.5, 13.5, 17.5])

## 2.Sum

In [5]:
arr.sum()

np.int64(190)

In [6]:
arr.sum(0)

array([40, 45, 50, 55])

## 3. cumsum
compute the cumulative sum row-wise (axis=1) or column-wise (axis=0).
### a. First column:
    [1, 
    [1+4=5,
    [5+7=3,

### b. Second column (add all elements before it from the first row):
    [1, 2,
    [5, 2+5=7,
    [12, 7+8=15,
### c. Third Column:
    [1, 2, 3],
    [5, 7, 3+6=9],
    [7, 15, 9+9=18]

In [7]:
arr2 = np.arange(1, 10).reshape(3, 3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr2.cumsum(0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]])

## 4.cumprod
Cummlative product of elements starting from 1

In [9]:
arr.cumprod(1)

array([[    0,     0,     0,     0],
       [    4,    20,   120,   840],
       [    8,    72,   720,  7920],
       [   12,   156,  2184, 32760],
       [   16,   272,  4896, 93024]])