# Linear Algebra
Numpy can be used for calculating **matrix multiplication**, **decomposition**, **determinants**, and other square matrix math.

In [1]:
import numpy as np

## Dot product
Multiply two n-dimensional arrays using `arr1.dot(arr2)` function instead of `*` method.

In [6]:
x = np.arange(1, 7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
y = np.array([[6, 23], [-1, 7], [8, 9]])
y

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])

In [10]:
# dot product of x and y
x.dot(y)

array([[ 28,  64],
       [ 67, 181]])